language: c
sudo: false

python:
  - 2.7
  - 3.4

env:
  - TEST_TARGET=unit
  # - TEST_TARGET=integration

os:
  - linux
  - osx

install:

  # Install miniconda
  # -----------------
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
    export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  else
    export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3
  fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget ${CONDA_BASE}-3.7.0-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget ${CONDA_BASE}-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda update --quiet conda
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - source activate $ENV_NAME

  # Customise the testing environment
  # ---------------------------------
  - conda install -c conda-forge --quiet --file conda_requirements.txt

  - PREFIX=$HOME/miniconda/envs/$ENV_NAME

  # Output debug info
  - conda list
  - conda info -a

  # Install
  - python setup.py --quiet install

script:

  - if [[ $TEST_TARGET == 'unit' ]]; then
      python setup.py test;
    fi
  # Get test data, then run the integration tests
  - if [[ $TEST_TARGET == 'integration' ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir test_files;
      wget http://gws-access.ceda.ac.uk/public/cis/cis_repo_test_files.tar.gz;
      tar -xzvf cis_repo_test_files.tar.gz -C test_files;
      export CIS_DATA_HOME="$(pwd)/test_files";
      python setup.py test -i -p 0 -d;
    fi
